-d C:\Users\Ev\Documents\trafik_sinyalizasyon\impl\gwsynthesis\trafik_sinyalizasyon.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\Ev\Documents\trafik_sinyalizasyon\src\trafik_sinyalizasyon.cst
-cfg C:\Users\Ev\Documents\trafik_sinyalizasyon\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
